name: Generate Snake Graph

on:
  schedule:
    - cron: "0 0 * * *"  # every day at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ptky
          outputs: |
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate Snake Graph"
          branch: output
          file_pattern: dist/*
